var namespace_mass_calculator =
[
    [ "HelperClasses", "namespace_mass_calculator_1_1_helper_classes.html", "namespace_mass_calculator_1_1_helper_classes" ],
    [ "Interface", "namespace_mass_calculator_1_1_interface.html", "namespace_mass_calculator_1_1_interface" ],
    [ "AlloyCoppers", "class_mass_calculator_1_1_alloy_coppers.html", "class_mass_calculator_1_1_alloy_coppers" ],
    [ "AlloySteels", "class_mass_calculator_1_1_alloy_steels.html", "class_mass_calculator_1_1_alloy_steels" ],
    [ "Aluminium", "class_mass_calculator_1_1_aluminium.html", "class_mass_calculator_1_1_aluminium" ],
    [ "Angle", "class_mass_calculator_1_1_angle.html", "class_mass_calculator_1_1_angle" ],
    [ "Bar", "class_mass_calculator_1_1_bar.html", "class_mass_calculator_1_1_bar" ],
    [ "Beam", "class_mass_calculator_1_1_beam.html", "class_mass_calculator_1_1_beam" ],
    [ "Brass", "class_mass_calculator_1_1_brass.html", "class_mass_calculator_1_1_brass" ],
    [ "Bronz", "class_mass_calculator_1_1_bronz.html", "class_mass_calculator_1_1_bronz" ],
    [ "Channel", "class_mass_calculator_1_1_channel.html", "class_mass_calculator_1_1_channel" ],
    [ "Copper", "class_mass_calculator_1_1_copper.html", "class_mass_calculator_1_1_copper" ],
    [ "crtp", "struct_mass_calculator_1_1crtp.html", "struct_mass_calculator_1_1crtp" ],
    [ "Cylinder", "class_mass_calculator_1_1_cylinder.html", "class_mass_calculator_1_1_cylinder" ],
    [ "DxfShape", "class_mass_calculator_1_1_dxf_shape.html", "class_mass_calculator_1_1_dxf_shape" ],
    [ "Elipse", "class_mass_calculator_1_1_elipse.html", "class_mass_calculator_1_1_elipse" ],
    [ "HexagonBar", "class_mass_calculator_1_1_hexagon_bar.html", "class_mass_calculator_1_1_hexagon_bar" ],
    [ "Magnesium", "class_mass_calculator_1_1_magnesium.html", "class_mass_calculator_1_1_magnesium" ],
    [ "Material", "class_mass_calculator_1_1_material.html", "class_mass_calculator_1_1_material" ],
    [ "Nickel", "class_mass_calculator_1_1_nickel.html", "class_mass_calculator_1_1_nickel" ],
    [ "OctagonBar", "class_mass_calculator_1_1_octagon_bar.html", "class_mass_calculator_1_1_octagon_bar" ],
    [ "Pipe", "class_mass_calculator_1_1_pipe.html", "class_mass_calculator_1_1_pipe" ],
    [ "Plastic", "class_mass_calculator_1_1_plastic.html", "class_mass_calculator_1_1_plastic" ],
    [ "Shape", "class_mass_calculator_1_1_shape.html", "class_mass_calculator_1_1_shape" ],
    [ "Shape< int >", "class_mass_calculator_1_1_shape_3_01int_01_4.html", "class_mass_calculator_1_1_shape_3_01int_01_4" ],
    [ "Sheet", "class_mass_calculator_1_1_sheet.html", "class_mass_calculator_1_1_sheet" ],
    [ "SquareBar", "class_mass_calculator_1_1_square_bar.html", "class_mass_calculator_1_1_square_bar" ],
    [ "SquareTubing", "class_mass_calculator_1_1_square_tubing.html", "class_mass_calculator_1_1_square_tubing" ],
    [ "StainlessSteel", "class_mass_calculator_1_1_stainless_steel.html", "class_mass_calculator_1_1_stainless_steel" ],
    [ "Steel", "class_mass_calculator_1_1_steel.html", "class_mass_calculator_1_1_steel" ],
    [ "StlShape", "class_mass_calculator_1_1_stl_shape.html", "class_mass_calculator_1_1_stl_shape" ],
    [ "TBar", "class_mass_calculator_1_1_t_bar.html", "class_mass_calculator_1_1_t_bar" ],
    [ "Titanium", "class_mass_calculator_1_1_titanium.html", "class_mass_calculator_1_1_titanium" ],
    [ "Zinc", "class_mass_calculator_1_1_zinc.html", "class_mass_calculator_1_1_zinc" ]
];