name: Update Docs

on:
  push:
  pull_request:
    types: [closed]

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout documentation repository
        uses: actions/checkout@v3
        with:
          repository: MassCalculator/masscalculator-core
          ref: devel

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DBUILD_DOCS=ON

      - name: Build documentation
        run: cmake --build ${{github.workspace}}/build -t Doxygen

      - name: Remove old HTML
        run: rm -rf masscalculator.github.io/docs/masscalculator-core/devel/html

      - name: Copy new HTML
        run: cp -r ${{github.workspace}}/build/docs/docs/doxygen/html masscalculator.github.io/docs/masscalculator-core/devel/html

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update documentation"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          branch: master
          force: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
